export const PARAM = {
  ID: 'id',
  POST_ID: 'postId',
} as const;

export const PATH = {
  PREFIX: 'api',
  AUTH: {
    PREFIX: 'auth',
    LOGIN: 'login',
    LOGOUT: 'logout',
    ME: 'me',
    NEW_PASSWORD: 'new-password',
    PASSWORD_RECOVERY: 'password-recovery',
    REFRESH_TOKEN: 'refresh-token',
    REGISTRATION: 'registration',
    REG_CONFIRMATION: 'registration-confirmation',
    REG_EMAIL_RESENDING: 'registration-email-resending',
  },
  BLOGS: {
    PREFIX: 'blogs',
    SA_PREFIX: 'sa/blogs',
    SINGLE: `:${PARAM.ID}`,
    POSTS: `:${PARAM.ID}/posts`,
    POST: `:${PARAM.ID}/posts/:${PARAM.POST_ID}`,
  },
  COMMENTS: {
    PREFIX: 'comments',
    SINGLE: `:${PARAM.ID}`,
    LIKE_STATUS: `:${PARAM.ID}/like-status`,
  },
  DEVICES: {
    PREFIX: 'security/devices',
    SINGLE: `:${PARAM.ID}`,
  },
  GAME: {
    PREFIX: 'pair-game-quiz/pairs',
    SINGLE: `:${PARAM.ID}`,
    NEW: 'connection',
    MINE: 'my',
    CURRENT: 'my-current',
    ANSWER: 'my-current/answers',
    STATISTIC: 'my-statistic',
  },
  QUESTIONS: {
    SA_PREFIX: 'sa/quiz/questions',
    SINGLE: `:${PARAM.ID}`,
    SINGLE_PUBLISH: `:${PARAM.ID}/publish`,
  },
  POSTS: {
    PREFIX: 'posts',
    SINGLE: `:${PARAM.ID}`,
    COMMENTS: `:${PARAM.ID}/comments`,
    LIKE_STATUS: `:${PARAM.ID}/like-status`,
  },
  USERS: {
    PREFIX: 'sa/users',
    SINGLE: `:${PARAM.ID}`,
  },
  TESTING: {
    PREFIX: 'testing',
    ALL: 'all-data',
  },
} as const;

export const FULL_PATH = {
  BLOGS: `/${PATH.PREFIX}/${PATH.BLOGS.PREFIX}`,
  BLOG: `/${PATH.PREFIX}/${PATH.BLOGS.PREFIX}/${PATH.BLOGS.SINGLE}`,
  BLOG_POSTS: `/${PATH.PREFIX}/${PATH.BLOGS.PREFIX}/${PATH.BLOGS.POSTS}`,
  //
  SA_BLOGS: `/${PATH.PREFIX}/${PATH.BLOGS.SA_PREFIX}`,
  SA_BLOG: `/${PATH.PREFIX}/${PATH.BLOGS.SA_PREFIX}/${PATH.BLOGS.SINGLE}`,
  SA_BLOG_POSTS: `/${PATH.PREFIX}/${PATH.BLOGS.SA_PREFIX}/${PATH.BLOGS.POSTS}`,
  SA_BLOG_POST: `/${PATH.PREFIX}/${PATH.BLOGS.SA_PREFIX}/${PATH.BLOGS.POST}`,
  //
  COMMENTS: `/${PATH.PREFIX}/${PATH.COMMENTS.PREFIX}`,
  COMMENT: `/${PATH.PREFIX}/${PATH.COMMENTS.PREFIX}/${PATH.COMMENTS.SINGLE}`,
  COMMENT_LIKE_STATUS: `/${PATH.PREFIX}/${PATH.COMMENTS.PREFIX}/${PATH.COMMENTS.LIKE_STATUS}`,
  //
  DEVICES: `/${PATH.PREFIX}/${PATH.DEVICES.PREFIX}`,
  DEVICE: `/${PATH.PREFIX}/${PATH.DEVICES.PREFIX}/${PATH.DEVICES.SINGLE}`,
  //
  GAMES: `/${PATH.PREFIX}/${PATH.GAME.PREFIX}`,
  GAME: `/${PATH.PREFIX}/${PATH.GAME.PREFIX}/${PATH.GAME.SINGLE}`,
  GAME_NEW: `/${PATH.PREFIX}/${PATH.GAME.PREFIX}/${PATH.GAME.NEW}`,
  GAME_CURRENT: `/${PATH.PREFIX}/${PATH.GAME.PREFIX}/${PATH.GAME.CURRENT}`,
  GAME_ADD_ANSWER: `/${PATH.PREFIX}/${PATH.GAME.PREFIX}/${PATH.GAME.ANSWER}`,
  GAMES_USER_STATS: `/${PATH.PREFIX}/${PATH.GAME.PREFIX}/${PATH.GAME.STATISTIC}`,
  GAMES_USER: `/${PATH.PREFIX}/${PATH.GAME.PREFIX}/${PATH.GAME.MINE}`,
  //
  SA_QUESTIONS: `/${PATH.PREFIX}/${PATH.QUESTIONS.SA_PREFIX}`,
  SA_QUESTION: `/${PATH.PREFIX}/${PATH.QUESTIONS.SA_PREFIX}/${PATH.QUESTIONS.SINGLE}`,
  SA_QUESTION_PUBLISH: `/${PATH.PREFIX}/${PATH.QUESTIONS.SA_PREFIX}/${PATH.QUESTIONS.SINGLE_PUBLISH}`,
  //
  POSTS: `/${PATH.PREFIX}/${PATH.POSTS.PREFIX}`,
  POST: `/${PATH.PREFIX}/${PATH.POSTS.PREFIX}/${PATH.POSTS.SINGLE}`,
  POST_COMMENTS: `/${PATH.PREFIX}/${PATH.POSTS.PREFIX}/${PATH.POSTS.COMMENTS}`,
  POST_LIKE_STATUS: `/${PATH.PREFIX}/${PATH.POSTS.PREFIX}/${PATH.POSTS.LIKE_STATUS}`,
  //
  LOGIN: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.LOGIN}`,
  LOGOUT: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.LOGOUT}`,
  ME: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.ME}`,
  NEW_PASSWORD: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.NEW_PASSWORD}`,
  PASSWORD_RECOVERY: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.PASSWORD_RECOVERY}`,
  REFRESH_TOKEN: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.REFRESH_TOKEN}`,
  REGISTRATION: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.REGISTRATION}`,
  REG_CONFIRMATION: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.REG_CONFIRMATION}`,
  REG_EMAIL_RESENDING: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.REG_EMAIL_RESENDING}`,
  //
  USERS: `/${PATH.PREFIX}/${PATH.USERS.PREFIX}`,
  USER: `/${PATH.PREFIX}/${PATH.USERS.PREFIX}/${PATH.USERS.SINGLE}`,
  //
  TESTING_ALL: `/${PATH.PREFIX}/${PATH.TESTING.PREFIX}/${PATH.TESTING.ALL}`,
} as const satisfies Record<string, string>;
