export const PARAM = {
  ID: 'id',
} as const;

export const PATH = {
  PREFIX: 'api',
  AUTH: {
    PREFIX: 'auth',
    LOGIN: 'login',
    LOGOUT: 'logout',
    ME: 'me',
    NEW_PASSWORD: 'new-password',
    PASSWORD_RECOVERY: 'password-recovery',
    REFRESH_TOKEN: 'refresh-token',
    REGISTRATION: 'registration',
    REG_CONFIRMATION: 'registration-confirmation',
    REG_EMAIL_RESENDING: 'registration-email-resending',
  },
  BLOGS: {
    PREFIX: 'blogs',
    SINGLE: `:${PARAM.ID}`,
    POSTS: `:${PARAM.ID}/posts`,
  },
  COMMENTS: {
    PREFIX: 'comments',
    SINGLE: `:${PARAM.ID}`,
    LIKE_STATUS: `:${PARAM.ID}/like-status`,
  },
  DEVICES: {
    PREFIX: 'security/devices',
    SINGLE: `:${PARAM.ID}`,
  },
  POSTS: {
    PREFIX: 'posts',
    SINGLE: `:${PARAM.ID}`,
    COMMENTS: `:${PARAM.ID}/comments`,
    LIKE_STATUS: `:${PARAM.ID}/like-status`,
  },
  USERS: {
    PREFIX: 'users',
    SINGLE: `:${PARAM.ID}`,
  },
  TESTING: {
    PREFIX: 'testing',
    ALL: 'all-data',
  },
} as const;

export const FULL_PATH = {
  BLOGS: `/${PATH.PREFIX}/${PATH.BLOGS.PREFIX}`,
  BLOG: `/${PATH.PREFIX}/${PATH.BLOGS.PREFIX}/${PATH.BLOGS.SINGLE}`,
  BLOG_POST: `/${PATH.PREFIX}/${PATH.BLOGS.PREFIX}/${PATH.BLOGS.POSTS}`,
  //
  COMMENTS: `/${PATH.PREFIX}/${PATH.COMMENTS.PREFIX}`,
  COMMENT: `/${PATH.PREFIX}/${PATH.COMMENTS.PREFIX}/${PATH.COMMENTS.SINGLE}`,
  COMMENT_LIKE_STATUS: `/${PATH.PREFIX}/${PATH.COMMENTS.PREFIX}/${PATH.COMMENTS.LIKE_STATUS}`,
  //
  DEVICES: `/${PATH.PREFIX}/${PATH.DEVICES.PREFIX}`,
  DEVICE: `/${PATH.PREFIX}/${PATH.DEVICES.PREFIX}/${PATH.DEVICES.SINGLE}`,
  //
  POSTS: `/${PATH.PREFIX}/${PATH.POSTS.PREFIX}`,
  POST: `/${PATH.PREFIX}/${PATH.POSTS.PREFIX}/${PATH.POSTS.SINGLE}`,
  POST_COMMENTS: `/${PATH.PREFIX}/${PATH.POSTS.PREFIX}/${PATH.POSTS.COMMENTS}`,
  POST_LIKE_STATUS: `/${PATH.PREFIX}/${PATH.POSTS.PREFIX}/${PATH.POSTS.LIKE_STATUS}`,
  //
  LOGIN: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.LOGIN}`,
  LOGOUT: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.LOGOUT}`,
  ME: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.ME}`,
  NEW_PASSWORD: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.NEW_PASSWORD}`,
  PASSWORD_RECOVERY: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.PASSWORD_RECOVERY}`,
  REFRESH_TOKEN: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.REFRESH_TOKEN}`,
  REGISTRATION: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.REGISTRATION}`,
  REG_CONFIRMATION: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.REG_CONFIRMATION}`,
  REG_EMAIL_RESENDING: `/${PATH.PREFIX}/${PATH.AUTH.PREFIX}/${PATH.AUTH.REG_EMAIL_RESENDING}`,
  //
  USERS: `/${PATH.PREFIX}/${PATH.USERS.PREFIX}`,
  USER: `/${PATH.PREFIX}/${PATH.USERS.PREFIX}/${PATH.USERS.SINGLE}`,
  //
  TESTING_ALL: `/${PATH.PREFIX}/${PATH.TESTING.PREFIX}/${PATH.TESTING.ALL}`,
} as const satisfies Record<string, string>;
